repos:
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [--max-line-length=160]
      - id: flake8
        name: flake8 autotabular
        files: autotabular/
      - id: flake8
        name: flake8 file-order-algorithms
        files: autotabular/algorithms
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 file-order-ensemble
        files: autotabular/ensembles
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 file-order-metrics
        files: autotabular/metrics
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 file-order-util
        files:  autotabular/util
        additional_dependencies:
          - flake8-import-order
      - id: flake8
        name: flake8 autotabular-test
        files: test/.*
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "160"]
