site_name: AutoML mljar-supervised

theme:
    name: material
    #custom_dir: overrides
    favicon: images/favicon.png
    icon:
        repo: fontawesome/brands/github-square
        logo: fontawesome/solid/book-open
    palette:
        primary: blue


repo_url: https://github.com/mljar/mljar-supervised
repo_name: mljar-supervised

markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
    - toc:
        permalink: true
    - codehilite
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - attr_list
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - footnotes

plugins:
  - search
  - mkdocstrings

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/mljar/mljar-supervised
        - icon: fontawesome/brands/slack
          link: https://mljar-supervised.slack.com/join/shared_invite/zt-gkhfsvhw-H6LMKxxV5adeTmn9V7nbZw#/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/MLJARofficial
        - icon: fontawesome/regular/lightbulb
          link: https://mljar.com
    font:
        - text: 'Ubuntu'
        - code: 'Ubuntu Mono'

edit_uri: https://github.com/mljar/docs/edit/master/docs/

copyright: Copyright Â© MLJAR, Inc.

extra_css:
  - stylesheets/extra.css

nav:
  - Get started: index.md
  - Features:
    - Steps of AutoML: features/automl.md
    - AutoML modes: features/modes.md
    - Golden Features: features/golden_features.md
    - Features Selection: features/features_selection.md
    - Algorithms: features/algorithms.md
    - Automated EDA: features/eda.md
    - Explainability: features/explain.md

  - Get help: get_help.md
  - How can you help?: help.md
  - Contributing: contributing.md
  - AutoML API: api.md
  - Roadmap: roadmap.md
  - Tutorials:
    - Classify Titanic Passangers: tutorials/titanic.md
    - Classify Random Data: tutorials/random.md
